# Generated by Django 2.2 on 2019-04-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('username', models.CharField(db_column='userName', max_length=25)),
                ('emailid', models.CharField(db_column='emailId', max_length=50, primary_key=True, serialize=False)),
                ('phoneno', models.CharField(db_column='phoneNo', max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(auto_now=True, db_column='dateTime', null=True)),
            ],
            options={
                'db_table': 'userData',
            },
        ),
    ]
